set( APPLICATION_SHORTNAME  "FileGo" )
set( APPLICATION_NAME       "FileGo" )
set( APPLICATION_EXECUTABLE "FileGo"        )
set( APPLICATION_DOMAIN     "FileGo.co"    )
set( APPLICATION_VENDOR     "FileGo, Inc"   )
set( THEME_CLASS            "ownCloudTheme"   )
set( APPLICATION_REV_DOMAIN "com.owncloud.desktopclient" )
set( WIN_SETUP_BITMAP_PATH  "${CMAKE_SOURCE_DIR}/admin/win/nsi" )
# set( THEME_INCLUDE          "${OEM_THEME_DIR}/mytheme.h" )
# set( APPLICATION_LICENSE    "${OEM_THEME_DIR}/license.txt )
